name: Build and deploy JAR app to Azure Web App - atletismonacional

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Build with Maven
        run: |
          cd project
          mvn clean install

      - name: List files in target directory for debugging
        run: |
          ls -la project/target

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: project/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: List files in workspace after downloading artifact
        run: |
          ls -la

      - name: List files in java-app directory for debugging
        run: |
          ls -la java-app

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_10A85E13372347809585942FECEA846D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F1486159F8704367BB6640CEB57087CE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69F9FDFB52494863938898AD30848507 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'atletismonacional'
          slot-name: 'Production'
          package: java-app/*.jar

          
